version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: baseball-batch.app
    env_file:
      - ./app/.env
    volumes:
      - ./app:/app
    tty:
      true
  db:
    image: mysql:latest
    container_name: baseball-batch.db
    ports:
      - 3306:3306
    env_file:
      - ./db/.env
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/init.db:/docker-entrypoint-initdb.d
